#! /bin/sh

# Description: Startup script for php-fpm on Debian. Place in /etc/init.d and
# run 'update-rc.d php-fpm defaults'.

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="php-fpm daemon"
NAME=php-fpm
#php-fpm路径
DAEMON=/usr/local/php56/sbin/$NAME
#配置文件路径
CONFIGFILE=/usr/local/php56/etc/php-fpm.conf
#PID文件路径(在php-fpm.conf设置)
PIDFILE=/usr/local/php56/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

d_start() {
  $DAEMON -y $CONFIGFILE || echo -n " already running"
}

d_stop() {
  kill -QUIT `cat $PIDFILE` || echo -n " not running"
}

d_reload() {
  kill -HUP `cat $PIDFILE` || echo -n " can't reload"
}

case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        d_start
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        d_stop
        echo "."
        ;;
  reload)
        echo -n "Reloading $DESC configuration..."
        d_reload
        echo "reloaded."
  ;;
  restart)
        echo -n "Restarting $DESC: $NAME"
        d_stop
        sleep 1
        d_start
        echo "."
        ;;
  *)
         echo "Usage: $0 {start|stop|restart|reload}" >&2
         exit 3
        ;;
esac

exit 0
